package com.acadlink.backend.common;

public enum ErrorCode {
    UNIVERSITY_EMAIL_EXISTS,
    INVALID_CREDENTIALS,
    USER_NOT_FOUND,
    VALIDATION_FAILED,
    INTERNAL_SERVER_ERROR,
    JWT_EXPIRED,
    JWT_INVALID,
    AUTH_INVALID_CREDENTIALS,
    UNIVERSITY_SIGNUP_VALIDATION_ERROR,
    UNIVERSITY_SIGNUP_INTERNAL_ERROR,
    STUDENT_SIGNUP_VALIDATION_ERROR,
    STUDENT_SIGNUP_INTERNAL_ERROR,
    PROFESSOR_SIGNUP_VALIDATION_ERROR,
    Professor_SIGNUP_INTERNAL_ERROR
}
